In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
#1
a = np.arange(12, 24, 1)
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [18]:
#2
b1 = a.reshape(3, 4)
b2 = a.reshape(4, 3)
b3 = a.reshape(2, 6)
b4 = a.reshape(6, 2)
b5 = a.reshape(12, 1)
#b1, b2, b3, b4, b5

In [25]:
#3 
b1 = a.reshape(3, -1)
b2 = a.reshape(4, -1)
b3 = a.reshape(-1, 6)
b4 = a.reshape(-1, 2)
b5 = a.reshape(12, -1)
#b1, b2, b3, b4, b5

In [ ]:
#4
Да, будет вектор


In [32]:
#5

mu, sigma = 0, 1
s = np.random.normal(mu, sigma, 12)
a = s.reshape(3, -1)
a


array([[-1.07804314,  0.76164276,  0.67345122,  1.88340976],
       [-1.70338134, -0.71544807,  0.55922418, -0.74801965],
       [ 0.70927455,  0.56817703, -1.4048878 ,  1.64500457]])

In [35]:
s.size
a.size
s.size == a.size


True

In [56]:
#6
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [57]:
#7
b = np.arange(20, 1, -2)
b = np.matrix(b)

c = np.transpose(b)
c

matrix([[20],
        [18],
        [16],
        [14],
        [12],
        [10],
        [ 8],
        [ 6],
        [ 4],
        [ 2]])

In [60]:
a == c.T


matrix([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
          True]])

In [75]:
#8
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b))
v.size

10

In [135]:
#9
a = np.arange(1, 13, 1)
A = a.reshape(4, 3)

At = A.T
B = A.dot(At)



array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

In [87]:
B.size

16

In [145]:
B_inv = np.linalg.inv(B)
B_inv

matrix([[ 9.35339320e+13, -1.89435812e+12, -2.76813080e+14,
          1.85173506e+14],
        [-6.76285848e+14,  7.89000156e+14,  4.50857232e+14,
         -5.63571540e+14],
        [ 1.07196990e+15, -1.57231724e+15, -7.12752241e+13,
          5.71622562e+14],
        [-4.89217984e+14,  7.85211439e+14, -1.02768928e+14,
         -1.93224528e+14]])

In [138]:
b = np.array([B])
Bt = b.T
Bt


array([[[ 14],
        [ 32],
        [ 50],
        [ 68]],

       [[ 32],
        [ 77],
        [122],
        [167]],

       [[ 50],
        [122],
        [194],
        [266]],

       [[ 68],
        [167],
        [266],
        [365]]])

In [101]:
#10
np.random.seed(42)

In [169]:
#11
a = np.random.randint(16, size=16)
a

array([ 4, 14, 13,  2,  0,  4,  9,  6, 14, 13,  6, 10,  8, 14, 14,  9])

In [115]:
#12
C = a.reshape(4, -1)
C

array([[ 1,  0, 15,  6],
       [ 6, 13,  7,  4],
       [ 2, 11,  7,  5],
       [10,  2,  0,  2]])

In [140]:
a = np.matrix(C)
C = a.T
C = C + 10
C

matrix([[11, 10, 25, 16],
        [16, 23, 17, 14],
        [12, 21, 17, 15],
        [20, 12, 10, 12]])

In [142]:
D = np.add(B, C)
D

matrix([[ 25,  42,  75,  84],
        [ 48, 100, 139, 181],
        [ 62, 143, 211, 281],
        [ 88, 179, 276, 377]])

In [146]:
D_inv = np.linalg.inv(D)
D_inv

matrix([[ 0.00876377,  0.08581217, -0.1278748 ,  0.0521609 ],
        [-0.03897192,  0.05588517,  0.03096686, -0.04122882],
        [ 0.07666133, -0.0430274 ,  0.04621055, -0.03086673],
        [-0.03966516, -0.0150646 , -0.01868488,  0.03264991]])

In [174]:
#Определитель матрицы
np.linalg.det(D).round()

519297.0

In [175]:
#Ранг матрицы
np.linalg.matrix_rank(D)

4

In [176]:
#13 
D_inv = l
l[l<=0] = 0
l[l>0] = 1
l

matrix([[1., 1., 0., 1.],
        [0., 1., 1., 0.],
        [1., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [177]:
E = np.where(l, B, C)
E

array([[ 14,  32,  25,  68],
       [ 16,  77, 122,  14],
       [ 50,  21, 194,  15],
       [ 20,  12,  10, 365]])